import { callLLM } from "@/lib/gemini";
import { CODEGEN_PROMPT } from "@/lib/prompts";

const FALLBACK_REGISTRY = {
  notion: {
    apiUrl: "https://api.notion.com/v1/search",
    httpMethod: "post",
    headersDict:
      '{"Authorization": f"Bearer {BEARER_TOKEN}", "Notion-Version": "2022-06-28", "Content-Type": "application/json"}',
  },
  github: {
    apiUrl: "https://api.github.com",
    httpMethod: "get",
    headersDict:
      '{"Authorization": f"token {API_KEY}", "Accept": "application/vnd.github.v3+json"}',
  },
};

const GENERIC_FALLBACK = {
  apiUrl: "https://example.com/api",
  httpMethod: "get",
  headersDict: "{}",
};

function cleanCode(raw) {
  let cleaned = raw.trim();
  if (cleaned.startsWith("```python")) {
    cleaned = cleaned.slice("```python".length).trim();
  } else if (cleaned.startsWith("```")) {
    cleaned = cleaned.slice(3).trim();
  }
  if (cleaned.endsWith("```")) {
    cleaned = cleaned.slice(0, -3).trim();
  }
  return cleaned;
}

function pythonType(jsonType) {
  const map = {
    string: "str",
    integer: "int",
    number: "float",
    boolean: "bool",
    array: "list",
    object: "dict",
  };
  return map[jsonType] || "str";
}

function renderConfig(toolSpec) {
  const toolName = toolSpec.tool_name || "generated_tool";
  const authType = toolSpec.auth_type || "none";

  const env = {};
  if (["api_key", "bearer", "oauth"].includes(authType)) {
    env[`${toolName.toUpperCase()}_API_KEY`] = "YOUR_API_KEY_HERE";
  }

  const envBlock =
    Object.keys(env).length > 0
      ? `,\n      "env": ${JSON.stringify(env, null, 8)}`
      : "";

  return `{
  "mcpServers": {
    "${toolName}": {
      "command": "python",
      "args": ["server.py"]${envBlock}
    }
  }
}`;
}

export async function generateCode(toolSpec, validationFeedback) {
  let userMsg = `Tool Specification:\n${JSON.stringify(toolSpec, null, 2)}`;
  if (validationFeedback) {
    userMsg += `\n\nPREVIOUS ATTEMPT FAILED VALIDATION. Fix these errors:\n${validationFeedback}`;
  }

  const raw = await callLLM({
    systemPrompt: CODEGEN_PROMPT,
    userMessage: userMsg,
    maxTokens: 4096,
    temperature: 0.0,
  });

  const serverCode = cleanCode(raw);
  if (!serverCode || serverCode.length < 50) {
    throw new Error("CodeGen returned empty or suspiciously short code");
  }

  const configJson = renderConfig(toolSpec);
  return { serverCode, configJson };
}

export function generateFallback(toolSpec) {
  const toolName = toolSpec.tool_name || "generated_tool";
  const description = toolSpec.description || "A generated MCP tool";
  const authType = toolSpec.auth_type || "none";
  const externalApi = toolSpec.external_api || null;
  const inputProps = toolSpec.input_schema?.properties || {};
  const keySteps = toolSpec.key_logic_steps || [];

  const inputParams =
    Object.entries(inputProps)
      .map(([name, prop]) => `${name}: ${pythonType(prop.type || "string")}`)
      .join(", ") || "query: str";

  const apiName = (externalApi || "").toLowerCase();
  const fb = FALLBACK_REGISTRY[apiName] || GENERIC_FALLBACK;

  const importOs = authType !== "none" ? "import os\n" : "";
  const importHttpx = externalApi ? "import httpx\n" : "";

  let authBlock = "";
  if (authType === "api_key") {
    const envKey = `${toolName.toUpperCase()}_API_KEY`;
    authBlock = `\nAPI_KEY = os.environ.get("${envKey}", "")\nif not API_KEY:\n    raise EnvironmentError("${envKey} environment variable is required")\n`;
  } else if (authType === "bearer") {
    const envKey = `${toolName.toUpperCase()}_TOKEN`;
    authBlock = `\nBEARER_TOKEN = os.environ.get("${envKey}", "")\nif not BEARER_TOKEN:\n    raise EnvironmentError("${envKey} environment variable is required")\n`;
  }

  const stepsBlock = keySteps
    .map((s, i) => `    # Step ${i + 1}: ${s}`)
    .join("\n");

  let bodyBlock;
  if (externalApi) {
    bodyBlock = `    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            headers = ${fb.headersDict}
            response = await client.${fb.httpMethod}(
                "${fb.apiUrl}",
                headers=headers,
            )
            response.raise_for_status()
            data = response.json()
            return {"success": True, "data": data}
    except httpx.HTTPStatusError as e:
        return {"success": False, "error": f"HTTP {e.response.status_code}: {e.response.text[:200]}"}
    except httpx.RequestError as e:
        return {"success": False, "error": f"Request failed: {str(e)}"}`;
  } else {
    bodyBlock = `    return {"success": True, "message": "${toolName} executed", "result": "Not yet implemented"}`;
  }

  const serverCode = `"""${toolName} MCP Server
Generated by AgentForge
${description}
"""
from mcp.server.fastmcp import FastMCP
${importOs}${importHttpx}import json

mcp = FastMCP("${toolName}")
${authBlock}

@mcp.tool()
async def ${toolName}(${inputParams}) -> dict:
    """${description}"""
${stepsBlock}
${bodyBlock}


if __name__ == "__main__":
    mcp.run(transport="stdio")
`;

  const configJson = renderConfig(toolSpec);
  return { serverCode, configJson };
}
